version: '3.8'

networks:
  isa-network:
    driver: bridge

volumes:
  consul-data:
  redis-data:
  minio-data:
  supabase-db-data:
  supabase-storage-data:

services:
  # ============== Infrastructure Services ==============
  
  # Consul Service Discovery
  consul:
    image: consul:latest
    container_name: isa-consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -ui -client=0.0.0.0
    networks:
      - isa-network
    volumes:
      - consul-data:/consul/data

  # NATS Message Queue Cluster
  nats-1:
    image: nats:latest
    container_name: isa-cloud-nats-1
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://nats-2:6222,nats://nats-3:6222"
    networks:
      - isa-network

  nats-2:
    image: nats:latest
    container_name: isa-cloud-nats-2
    ports:
      - "4223:4222"
      - "6223:6222"
      - "8223:8222"
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://nats-1:6222,nats://nats-3:6222"
    networks:
      - isa-network

  nats-3:
    image: nats:latest
    container_name: isa-cloud-nats-3
    ports:
      - "4224:4222"
      - "6224:6222"
      - "8224:8222"
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://nats-1:6222,nats://nats-2:6222"
    networks:
      - isa-network

  # ============== Supabase Stack ==============
  # Supabase includes PostgreSQL, Auth, Storage, Realtime, etc.
  
  supabase-db:
    image: public.ecr.aws/supabase/postgres:17.4.1.043
    container_name: supabase_db_local
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "54322:5432"
    volumes:
      - supabase-db-data:/var/lib/postgresql/data
    networks:
      - isa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  supabase-kong:
    image: public.ecr.aws/supabase/kong:2.8.1
    container_name: supabase_kong_local
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/var/lib/kong/kong.yml"
    ports:
      - "54321:8000"
    volumes:
      - ./supabase/volumes/kong:/var/lib/kong
    depends_on:
      - supabase-db
    networks:
      - isa-network

  supabase-auth:
    image: public.ecr.aws/supabase/gotrue:v2.176.1
    container_name: supabase_auth_local
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: http://localhost:54321
      GOTRUE_DB_DATABASE_URL: postgres://postgres:postgres@supabase-db:5432/postgres
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_JWT_SECRET: "super-secret-jwt-token-with-at-least-32-characters-long"
      GOTRUE_JWT_EXP: 3600
    depends_on:
      - supabase-db
    networks:
      - isa-network

  supabase-rest:
    image: public.ecr.aws/supabase/postgrest:v12.2.12
    container_name: supabase_rest_local
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@supabase-db:5432/postgres
      PGRST_DB_SCHEMAS: public,storage,dev
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: "super-secret-jwt-token-with-at-least-32-characters-long"
    depends_on:
      - supabase-db
    networks:
      - isa-network

  supabase-realtime:
    image: public.ecr.aws/supabase/realtime:v2.36.18
    container_name: supabase_realtime_local
    environment:
      DB_HOST: supabase-db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SSL: "false"
      JWT_SECRET: "super-secret-jwt-token-with-at-least-32-characters-long"
    depends_on:
      - supabase-db
    networks:
      - isa-network

  supabase-storage:
    image: public.ecr.aws/supabase/storage-api:v1.24.6
    container_name: supabase_storage_local
    environment:
      DATABASE_URL: postgres://postgres:postgres@supabase-db:5432/postgres
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      JWT_SECRET: "super-secret-jwt-token-with-at-least-32-characters-long"
      ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
    volumes:
      - supabase-storage-data:/var/lib/storage
    depends_on:
      - supabase-db
    networks:
      - isa-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: isa-redis
    ports:
      - "6379:6379"
    networks:
      - isa-network

  # MinIO Object Storage (for non-Supabase storage needs)
  minio:
    image: minio/minio:latest
    container_name: isa-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - isa-network

  # ============== Blockchain Services (Development Only) ==============
  
  blockchain-node:
    build:
      context: ../isA_Chain
      dockerfile: ../isA_Cloud/deployments/dockerfiles/Dockerfile.blockchain
    container_name: isa-blockchain-node
    ports:
      - "8545:8545"
      - "8311:8311"  # DeFi API
      - "8312:8312"  # NFT API
      - "8315:8315"  # Tools API
    networks:
      - isa-network
    depends_on:
      - consul
      - supabase-db
    profiles: ["development"]  # Only start in development profile

  # ============== AI Services ==============
  
  mcp:
    build:
      context: ../isA_MCP
      dockerfile: ../isA_Cloud/deployments/dockerfiles/Dockerfile.mcp
      args:
        - mcp_source=.
    container_name: isa-mcp
    ports:
      - "8081:8081"
    environment:
      - MCP_PORT=8081
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - DATABASE_URL=postgresql://postgres:postgres@supabase-db:5432/postgres?options=-c%20search_path%3Ddev
      - SUPABASE_LOCAL_URL=http://supabase-kong:8000
      - SUPABASE_LOCAL_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - SUPABASE_LOCAL_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      - PYTHONUNBUFFERED=1
    networks:
      - isa-network
    depends_on:
      - consul
      - supabase-db
      - redis

  model:
    build:
      context: ../isA_Model
      dockerfile: ../isA_Cloud/deployments/dockerfiles/Dockerfile.model
      args:
        - model_source=.
    container_name: isa-model
    ports:
      - "8082:8082"
    environment:
      - ISA_API_URL=http://model:8082
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - DATABASE_URL=postgresql://postgres:postgres@supabase-db:5432/postgres?options=-c%20search_path%3Ddev
      - SUPABASE_LOCAL_URL=http://supabase-kong:8000
      - SUPABASE_LOCAL_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - PYTHONUNBUFFERED=1
    networks:
      - isa-network
    depends_on:
      - consul
      - supabase-db
      - mcp

  agent:
    build:
      context: ../isA_Agent
      dockerfile: ../isA_Cloud/deployments/dockerfiles/Dockerfile.agent
      args:
        - agent_source=.
    container_name: isa-agent
    ports:
      - "8083:8083"
    environment:
      - AGENT_PORT=8083
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - MCP_URL=http://mcp:8081
      - MODEL_URL=http://model:8082
      - DATABASE_URL=postgresql://postgres:postgres@supabase-db:5432/postgres?options=-c%20search_path%3Ddev
      - SUPABASE_LOCAL_URL=http://supabase-kong:8000
      - SUPABASE_LOCAL_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - PYTHONUNBUFFERED=1
    networks:
      - isa-network
    depends_on:
      - consul
      - supabase-db
      - mcp
      - model

  # ============== User Microservices ==============
  
  account-service:
    build:
      context: ../isA_user
      dockerfile: ../isA_Cloud/deployments/dockerfiles/Dockerfile.user-base
    container_name: isa-account
    ports:
      - "8201:8201"
    environment:
      - SERVICE_NAME=account
      - SERVICE_PORT=8201
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - DATABASE_URL=postgresql://postgres:postgres@supabase-db:5432/postgres?options=-c%20search_path%3Ddev
      - SUPABASE_LOCAL_URL=http://supabase-kong:8000
      - SUPABASE_LOCAL_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - REDIS_URL=redis://redis:6379
    command: ["python", "-m", "uvicorn", "microservices.account_service.main:app", "--host", "0.0.0.0", "--port", "8201"]
    networks:
      - isa-network
    depends_on:
      - consul
      - supabase-db
      - redis

  auth-service:
    build:
      context: ../isA_user
      dockerfile: ../isA_Cloud/deployments/dockerfiles/Dockerfile.user-base
    container_name: isa-auth
    ports:
      - "8202:8202"
    environment:
      - SERVICE_NAME=auth
      - SERVICE_PORT=8202
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - DATABASE_URL=postgresql://postgres:postgres@supabase-db:5432/postgres?options=-c%20search_path%3Ddev
      - SUPABASE_LOCAL_URL=http://supabase-kong:8000
      - SUPABASE_LOCAL_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - REDIS_URL=redis://redis:6379
    command: ["python", "-m", "uvicorn", "microservices.auth_service.main:app", "--host", "0.0.0.0", "--port", "8202"]
    networks:
      - isa-network
    depends_on:
      - consul
      - supabase-db
      - redis

  authorization-service:
    build:
      context: ../isA_user
      dockerfile: ../isA_Cloud/deployments/dockerfiles/Dockerfile.user-base
    container_name: isa-authorization
    ports:
      - "8203:8203"
    environment:
      - SERVICE_NAME=authorization
      - SERVICE_PORT=8203
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - DATABASE_URL=postgresql://postgres:postgres@supabase-db:5432/postgres?options=-c%20search_path%3Ddev
      - SUPABASE_LOCAL_URL=http://supabase-kong:8000
      - SUPABASE_LOCAL_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      - REDIS_URL=redis://redis:6379
    command: ["python", "-m", "uvicorn", "microservices.authorization_service.main:app", "--host", "0.0.0.0", "--port", "8203"]
    networks:
      - isa-network
    depends_on:
      - consul
      - supabase-db
      - redis

  # ... 其他user微服务配置类似 ...

  # ============== API Gateway ==============
  
  gateway:
    build:
      context: ../isA_Cloud
      dockerfile: deployments/dockerfiles/Dockerfile.gateway
    container_name: isa-gateway
    ports:
      - "8000:8000"
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - NATS_URL=nats://nats-1:4222,nats://nats-2:4222,nats://nats-3:4222
    networks:
      - isa-network
    depends_on:
      - consul
      - nats-1
      - nats-2
      - nats-3
      - supabase-kong
      - account-service
      - auth-service
      - mcp
      - model
      - agent
      - blockchain-node