# isA Platform Services Configuration
# This file defines all services managed by the deployment center

services:
  # Gateway Service (this repo)
  gateway:
    repo: https://github.com/xenophobed/isA_Cloud.git
    branch: main
    path: .
    dockerfile: deployments/dockerfiles/Dockerfile.gateway
    port: 8000
    healthcheck: /health
    ecr_repo: isa-gateway
    
  # AI/ML Services
  mcp:
    repo: https://github.com/xenophobed/isA_MCP.git
    branch: main
    path: ../isA_MCP
    dockerfile: deployments/dockerfiles/Dockerfile.mcp
    port: 8081
    healthcheck: /health
    ecr_repo: isa-mcp
    
  model:
    repo: https://github.com/xenophobed/isA_Model.git
    branch: main
    path: ../isA_Model
    dockerfile: deployments/dockerfiles/Dockerfile.model
    port: 8082
    healthcheck: /health
    ecr_repo: isa-model
    
  agent:
    repo: https://github.com/xenophobed/isA_Agent.git
    branch: main
    path: ../isA_Agent
    dockerfile: deployments/dockerfiles/Dockerfile.agent
    port: 8083
    healthcheck: /health
    ecr_repo: isa-agent
    
  # User Services (12 microservices)
  user:
    repo: https://github.com/xenophobed/isA_user.git
    branch: main
    path: ../isA_user
    dockerfile: deployments/dockerfiles/Dockerfile.user-base
    ports:
      - account: 8201
      - auth: 8202
      - authorization: 8203
      - audit: 8204
      - session: 8205
      - notification: 8206
      - payment: 8207
      - storage: 8208
      - wallet: 8209
      - order: 8210
      - task: 8211
      - organization: 8212
    healthcheck: /health
    ecr_repo: isa-user-base
    
  # Blockchain Services (Development only)
  blockchain:
    repo: https://github.com/xenophobed/isA_Chain.git
    branch: main
    path: ../isA_Chain
    dockerfile: deployments/dockerfiles/Dockerfile.blockchain
    ports:
      - hardhat: 8545
      - defi-api: 8311
      - nft-api: 8312
      - tools-api: 8315
    healthcheck: /health
    ecr_repo: isa-blockchain
    environments: [development, staging]  # Not deployed to production

# Deployment configuration
deployment:
  aws_region: us-east-1
  ecr_registry: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com
  ecs_cluster: isa-platform-cluster
  
# Notification settings for CI/CD
notifications:
  slack:
    webhook_url: ${SLACK_WEBHOOK_URL}
    channels:
      success: "#deployments"
      failure: "#alerts"