version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: isa_mqtt_broker
    ports:
      - "1883:1883"  # MQTT port
      - "9002:9002"  # WebSocket port
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - isa_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  mosquitto_data:
    driver: local
  mosquitto_log:
    driver: local

networks:
  isa_network:
    external: true