# IsA Cloud Gateway Configuration

app:
  name: "IsA Cloud Gateway"
  version: "1.0.0"

environment: "development"
debug: true

server:
  host: "0.0.0.0"
  http_port: 8000  # Gateway主端口
  grpc_port: 8001  # Gateway gRPC端口

services:
  user_service:
    host: "localhost"
    http_port: 8201  # Account服务端口
    grpc_port: 9201
    timeout: "30s"
    retry:
      max_attempts: 3
      backoff: "1s"

  auth_service:
    host: "localhost"
    http_port: 8202  # Auth服务端口
    grpc_port: 9202
    timeout: "10s"
    retry:
      max_attempts: 3
      backoff: "1s"

  agent_service:
    host: "localhost"
    http_port: 8080  # 现有isA_agent端口
    grpc_port: 9080
    timeout: "60s"
    retry:
      max_attempts: 2
      backoff: "2s"

  model_service:
    host: "localhost"
    http_port: 8082  # 现有isA_model端口
    grpc_port: 9082
    timeout: "120s"
    retry:
      max_attempts: 2
      backoff: "5s"

  mcp_service:
    host: "localhost"
    http_port: 8081  # 现有isA_mcp端口
    grpc_port: 9081
    timeout: "30s"
    retry:
      max_attempts: 3
      backoff: "1s"

database:
  host: "localhost"
  port: 5432
  database: "isa_cloud"
  username: "postgres"
  password: "password"
  ssl_mode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0

logging:
  level: "debug"
  format: "text"  # text for development, json for production
  output: "stdout"

monitoring:
  enabled: true
  port: 9090
  path: "/metrics"
  namespace: "isa_cloud"
  subsystem: "gateway"

security:
  cors:
    enabled: true
    allow_origins: 
      - "http://localhost:3000"
      - "http://localhost:5173"
      - "http://localhost:8000"
    allow_methods: 
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allow_headers: 
      - "Authorization"
      - "Content-Type"
      - "X-Request-ID"
      - "Cache-Control"
    allow_credentials: true

  rate_limit:
    enabled: true
    rps: 100
    burst: 200

  jwt:
    secret: "your-development-secret-key"
    expiration: "24h"
    issuer: "isa-cloud-gateway"

blockchain:
  enabled: true
  chains:
    isa_chain:
      rpc_endpoint: "http://localhost:8545"
      chain_id: 1337
      network_name: "isA_Chain"
      consensus_type: "hybrid"
      enabled: true
    ethereum:
      rpc_endpoint: "https://mainnet.infura.io/v3/YOUR_PROJECT_ID"
      chain_id: 1
      network_name: "Ethereum Mainnet"
      enabled: false
  default_chain: "isa_chain"
  private_key: ""  # Set in production environment
  gas_settings:
    default_gas_limit: 21000
    default_gas_price: "20000000000"  # 20 gwei
    max_gas_price: "100000000000"     # 100 gwei