version: '3.8'

services:
  nats-1:
    image: nats:2.10-alpine
    container_name: isa-cloud-nats-1
    command: 
      - "-c"
      - "/etc/nats/nats.conf"
    ports:
      - "4222:4222"  # Client connections
      - "6222:6222"  # Cluster connections
      - "8222:8222"  # HTTP monitoring
    volumes:
      - ./server/nats.conf:/etc/nats/nats.conf:ro
      - nats-data-1:/data
      - nats-logs-1:/var/log/nats
    networks:
      - isa-cloud-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats-2:
    image: nats:2.10-alpine
    container_name: isa-cloud-nats-2
    command:
      - "-c"
      - "/etc/nats/nats-2.conf"
    ports:
      - "4223:4222"
      - "6223:6222"
      - "8223:8222"
    volumes:
      - ./server/nats-2.conf:/etc/nats/nats-2.conf:ro
      - nats-data-2:/data
      - nats-logs-2:/var/log/nats
    networks:
      - isa-cloud-network
    restart: unless-stopped
    depends_on:
      - nats-1

  nats-3:
    image: nats:2.10-alpine
    container_name: isa-cloud-nats-3
    command:
      - "-c"
      - "/etc/nats/nats-3.conf"
    ports:
      - "4224:4222"
      - "6224:6222"
      - "8224:8222"
    volumes:
      - ./server/nats-3.conf:/etc/nats/nats-3.conf:ro
      - nats-data-3:/data
      - nats-logs-3:/var/log/nats
    networks:
      - isa-cloud-network
    restart: unless-stopped
    depends_on:
      - nats-1

  # NATS Box for testing and debugging
  nats-box:
    image: natsio/nats-box:latest
    container_name: isa-cloud-nats-box
    networks:
      - isa-cloud-network
    command: sleep 3600
    depends_on:
      - nats-1
      - nats-2
      - nats-3

volumes:
  nats-data-1:
    driver: local
  nats-data-2:
    driver: local
  nats-data-3:
    driver: local
  nats-logs-1:
    driver: local
  nats-logs-2:
    driver: local
  nats-logs-3:
    driver: local

networks:
  isa-cloud-network:
    driver: bridge
    name: isa-cloud-network